# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x12\x03rpc\"$\n\x06Server\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0b\x41\x64\x64Response\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"h\n\x07Request\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x1b\n\x06server\x18\x03 \x01(\x0b\x32\x0b.rpc.Server\x12\x1c\n\x03\x61\x64\x64\x18\x04 \x01(\x0b\x32\x0f.rpc.AddRequest\"f\n\x08Response\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x1c\n\x07servers\x18\x03 \x03(\x0b\x32\x0b.rpc.Server\x12\x1d\n\x03\x61\x64\x64\x18\x04 \x01(\x0b\x32\x10.rpc.AddResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVER._serialized_start=18
  _SERVER._serialized_end=54
  _ADDREQUEST._serialized_start=56
  _ADDREQUEST._serialized_end=90
  _ADDRESPONSE._serialized_start=92
  _ADDRESPONSE._serialized_end=118
  _REQUEST._serialized_start=120
  _REQUEST._serialized_end=224
  _RESPONSE._serialized_start=226
  _RESPONSE._serialized_end=328
# @@protoc_insertion_point(module_scope)
