# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x12\x03rpc\"I\n\x07Request\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\"G\n\x08Response\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x1c\n\x07servers\x18\x03 \x03(\x0b\x32\x0b.rpc.Server\"$\n\x06Server\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"8\n\nAddRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\t\n\x01\x61\x18\x02 \x01(\x05\x12\t\n\x01\x62\x18\x03 \x01(\x05\"\x1a\n\x0b\x41\x64\x64Response\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x32\x36\n\nCalculator\x12(\n\x03\x61\x64\x64\x12\x0f.rpc.AddRequest\x1a\x10.rpc.AddResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=18
  _REQUEST._serialized_end=91
  _RESPONSE._serialized_start=93
  _RESPONSE._serialized_end=164
  _SERVER._serialized_start=166
  _SERVER._serialized_end=202
  _ADDREQUEST._serialized_start=204
  _ADDREQUEST._serialized_end=260
  _ADDRESPONSE._serialized_start=262
  _ADDRESPONSE._serialized_end=288
  _CALCULATOR._serialized_start=290
  _CALCULATOR._serialized_end=344
# @@protoc_insertion_point(module_scope)
